import {
  Activity,
  Anchor,
  Atom,
  Axe,
  BicepsFlexed,
  Bike,
  Bolt,
  Bone,
  Candy,
  Castle,
  Cookie,
  Crosshair,
  Crown,
  Drumstick,
  Dumbbell,
  Feather,
  Flame,
  Footprints,
  Gem,
  Ghost,
  Hammer,
  HeartPulse,
  Hexagon,
  Moon,
  Mountain,
  Orbit,
  PersonStanding,
  Rocket,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Sword,
  Swords,
  Target,
  Timer,
  Trophy,
  Waves,
  Weight,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils/cn";

/** Pictograms users can pick for programs and exercises. Keys are stored in data. */
export const GLYPHS: Record<string, { icon: LucideIcon; label: string }> = {
  dumbbell: { icon: Dumbbell, label: "Haltère" },
  weight: { icon: Weight, label: "Poids" },
  biceps: { icon: BicepsFlexed, label: "Biceps" },
  person: { icon: PersonStanding, label: "Corps" },
  footprints: { icon: Footprints, label: "Pas" },
  flame: { icon: Flame, label: "Flamme" },
  zap: { icon: Zap, label: "Éclair" },
  bolt: { icon: Bolt, label: "Boulon" },
  swords: { icon: Swords, label: "Épées" },
  sword: { icon: Sword, label: "Lame" },
  axe: { icon: Axe, label: "Hache" },
  hammer: { icon: Hammer, label: "Marteau" },
  shield: { icon: Shield, label: "Bouclier" },
  crown: { icon: Crown, label: "Couronne" },
  skull: { icon: Skull, label: "Crâne" },
  ghost: { icon: Ghost, label: "Ombre" },
  mountain: { icon: Mountain, label: "Montagne" },
  rocket: { icon: Rocket, label: "Fusée" },
  target: { icon: Target, label: "Cible" },
  crosshair: { icon: Crosshair, label: "Viseur" },
  trophy: { icon: Trophy, label: "Trophée" },
  star: { icon: Star, label: "Étoile" },
  gem: { icon: Gem, label: "Gemme" },
  hexagon: { icon: Hexagon, label: "Hexagone" },
  sparkles: { icon: Sparkles, label: "Éclat" },
  atom: { icon: Atom, label: "Atome" },
  orbit: { icon: Orbit, label: "Orbite" },
  anchor: { icon: Anchor, label: "Ancre" },
  castle: { icon: Castle, label: "Donjon" },
  heart: { icon: HeartPulse, label: "Cardio" },
  activity: { icon: Activity, label: "Activité" },
  bike: { icon: Bike, label: "Vélo" },
  timer: { icon: Timer, label: "Chrono" },
  waves: { icon: Waves, label: "Vagues" },
  wind: { icon: Wind, label: "Souffle" },
  feather: { icon: Feather, label: "Plume" },
  bone: { icon: Bone, label: "Os" },
  sun: { icon: Sun, label: "Soleil" },
  moon: { icon: Moon, label: "Lune" },
  cookie: { icon: Cookie, label: "Biscuit" },
  candy: { icon: Candy, label: "Bonbon" },
  drumstick: { icon: Drumstick, label: "Viande" },
};

export type GlyphKey = keyof typeof GLYPHS;

export function GlyphIcon({ name, className, strokeWidth }: { name: string; className?: string; strokeWidth?: number }) {
  const Icon = GLYPHS[name]?.icon ?? Dumbbell;
  return <Icon className={cn("shrink-0", className)} strokeWidth={strokeWidth} aria-hidden />;
}
